# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import messaging_gateway_pb2 as messaging__gateway__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messaging_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessagingGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PollMessages = channel.unary_unary(
                '/claw_swarm.gateway.MessagingGateway/PollMessages',
                request_serializer=messaging__gateway__pb2.PollMessagesRequest.SerializeToString,
                response_deserializer=messaging__gateway__pb2.PollMessagesResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.unary_stream(
                '/claw_swarm.gateway.MessagingGateway/StreamMessages',
                request_serializer=messaging__gateway__pb2.StreamMessagesRequest.SerializeToString,
                response_deserializer=messaging__gateway__pb2.UnifiedMessage.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/claw_swarm.gateway.MessagingGateway/Health',
                request_serializer=messaging__gateway__pb2.HealthRequest.SerializeToString,
                response_deserializer=messaging__gateway__pb2.HealthResponse.FromString,
                _registered_method=True)


class MessagingGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PollMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PollMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PollMessages,
                    request_deserializer=messaging__gateway__pb2.PollMessagesRequest.FromString,
                    response_serializer=messaging__gateway__pb2.PollMessagesResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=messaging__gateway__pb2.StreamMessagesRequest.FromString,
                    response_serializer=messaging__gateway__pb2.UnifiedMessage.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=messaging__gateway__pb2.HealthRequest.FromString,
                    response_serializer=messaging__gateway__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'claw_swarm.gateway.MessagingGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('claw_swarm.gateway.MessagingGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessagingGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PollMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claw_swarm.gateway.MessagingGateway/PollMessages',
            messaging__gateway__pb2.PollMessagesRequest.SerializeToString,
            messaging__gateway__pb2.PollMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/claw_swarm.gateway.MessagingGateway/StreamMessages',
            messaging__gateway__pb2.StreamMessagesRequest.SerializeToString,
            messaging__gateway__pb2.UnifiedMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/claw_swarm.gateway.MessagingGateway/Health',
            messaging__gateway__pb2.HealthRequest.SerializeToString,
            messaging__gateway__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
